# Specify docker image
image: debian:stretch

# Define variable to disable SSL verification of GIT
variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - lint
  - codestyle
  - manpages
  - transifex
  - tarballs
  - trigger

## Stage lint

# PHP lint (jessie)
create_php_lint_rapport_jessie:
  image: php:5.6.33-cli-jessie
  stage: lint
  only:
    - branches
  script:
    - find . -type f -name '*.php' -o -name '*.inc' -print0 | xargs -0 -n1 php -l

# PHP lint (stretch)
create_php_lint_rapport_stretch:
  image: php:cli-stretch
  stage: lint
  only:
    - branches
  script:
    - find . -type f -name '*.php' -o -name '*.inc' -print0 | xargs -0 -n1 php -l

## Stage codestyle

# PHP codesniffer
create_php_code_sniffer_rapport_13:
  stage: codestyle
  only:
    - branches
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq  git php-cli php-codesniffer
  script:
    - git clone https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git -b 1.3 ../dev-tools
    - find . -type f -name '*.php' -o -name '*.inc' > ./filelist
    - phpcs --ignore=class_sieve.inc --standard=../dev-tools/php-codesniffer-rules/FDStandard/ruleset.xml --file-list=./filelist

# Sonar publishing
sonar_publish:
  image: sonar-cli:3.1.0.1141
  stage: codestyle
  only:
    - 1.3-dev
  script:
    - /home/sonar/*/bin/sonar-scanner
      -D sonar.projectKey=fusiondirectory-plugins-dev
      -D sonar.projectName=FusionDirectory-Plugins-Dev
      -D sonar.projectVersion=1.3
      -D sonar.sourceEncoding=UTF-8
      -D sonar.exclusions='mail/personal/mail/class_sieve.inc'
      -D sonar.gitlab.project_id="$CI_PROJECT_PATH"
      -D sonar.gitlab.commit_sha="$CI_COMMIT_SHA"
      -D sonar.gitlab.ref_name="$CI_COMMIT_REF_NAME"

# Sonar preview
sonar_preview:
  image: sonar-cli:3.1.0.1141
  stage: codestyle
  except:
    - 1.3-dev
  script:
    - /home/sonar/*/bin/sonar-scanner
      -D sonar.projectKey=fusiondirectory-plugins-dev
      -D sonar.projectName=FusionDirectory-Plugins-Dev
      -D sonar.projectVersion=1.3
      -D sonar.sourceEncoding=UTF-8
      -D sonar.exclusions='mail/personal/mail/class_sieve.inc'
      -D sonar.gitlab.project_id="$CI_PROJECT_PATH"
      -D sonar.gitlab.commit_sha="$CI_COMMIT_SHA"
      -D sonar.gitlab.ref_name="$CI_COMMIT_REF_NAME"
      -D sonar.analysis.mode=preview

# fusiondirectory-update-locale
fusiondirectory-update-locale:
  image: php:cli-stretch
  stage: transifex
  only:
    - branches
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq gettext git
  script:
    - git clone https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - ../dev-tools/locale-scripts/fusiondirectory-update-locale-plugins

# Update transifex
update-transifex:
  image: php:cli-stretch
  stage: transifex
  only:
    - /^1.*$/
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq gettext git transifex-client
  script:
    - git clone https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
    - tx pull -a -f
    - ../dev-tools/locale-scripts/fusiondirectory-update-locale-plugins
    - tx push -f -s -t --skip --no-interactive

build-tarballs:
  stage: tarballs
  script:
    - tar -cvzf fusiondirectory-plugins.tar.gz *
  artifacts:
    paths:
    - fusiondirectory-plugins.tar.gz
    expire_in: 1h

build-release:
  stage: tarballs
  only:
    - tags
  script: 
    - tar -cvzf fusiondirectory-plugins-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"').tar.gz *
  artifacts:
    paths:
      - fusiondirectory-plugins-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"').tar.gz

trigger-ci-debian-stretch:
  stage: trigger
  only:
    - master
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_DEBIAN_STRETCH: "$BRANCH_BUILD_DEBIAN_STRETCH"
  trigger:
    project: debian/stretch-fusiondirectory-release
    branch: "$BRANCH_BUILD_DEBIAN_STRETCH"

trigger-ci-debian-buster:
  stage: trigger
  only:
    - master
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_DEBIAN_BUSTER: "$BRANCH_BUILD_DEBIAN_BUSTER"
  trigger:
    project: debian/buster-fusiondirectory-release
    branch: "$BRANCH_BUILD_DEBIAN_BUSTER"

trigger-ci-centos7:
  stage: trigger
  only:
    - master
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_CENTOS_7: "$BRANCH_BUILD_CENTOS_7"
  trigger:
    project: centos/centos7-fusiondirectory-release
    branch: "$BRANCH_BUILD_CENTOS_7"
