# Specify docker image
image: debian:stretch

stages:
  - tarballs

build-release:
  stage: tarballs
  only:
    - master
  script:
    - VERSION=$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')
    - mkdir ../fusiondirectory-plugins-$VERSION/
    - mv ./* ../fusiondirectory-plugins-$VERSION/
    - mv  ../fusiondirectory-plugins-$VERSION/ ./
    - tar -cvzf fusiondirectory-plugins-$VERSION.tar.gz *
  artifacts:
    paths:
      - fusiondirectory-plugins-$VERSION.tar.gz
