stages:
  - lint
  - codestyle
  - manpages
  - transifex
  - tarballs
  - trigger

## Stage lint

# PHP lint (stretch)
create_php_lint_rapport_stretch:
  image: registry.fusiondirectory.org/fusiondirectory/fd-plugins/phpcodesniffer-cli:stretch
  stage: lint
  only:
    - branches
  script:
    - find . -type f -name '*.php' -o -name '*.inc' -print0 | xargs -0 -n1 php -l

## Stage codestyle

# PHP codesniffer
create_php_code_sniffer_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd-plugins/phpcodesniffer-cli:stretch
  stage: codestyle
  only:
    - branches
  script:
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git -b 1.3 ../dev-tools
    - find . -type f -name '*.php' -o -name '*.inc' > ./filelist
    - phpcs --ignore=class_sieve.inc --standard=../dev-tools/php-codesniffer-rules/FDStandard/ruleset.xml --file-list=./filelist

# fusiondirectory-update-locale
fusiondirectory-update-locale:
  image: registry.fusiondirectory.org/fusiondirectory/fd-plugins/transifex-cli:stretch
  stage: transifex
  only:
    - branches
  script:
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - ../dev-tools/locale-scripts/fusiondirectory-update-locale-plugins

# Update transifex
update-transifex:
  image: registry.fusiondirectory.org/fusiondirectory/fd-plugins/transifex-cli:stretch
  stage: transifex
  only:
    - /^1.*$/
  script:
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
    - tx pull -a -f
    - ../dev-tools/locale-scripts/fusiondirectory-update-locale-plugins
    - tx push -s -t --skip --no-interactive

build-tarballs:
  stage: tarballs
  only:
    - 1.3-fixes
  script:
    - mkdir ../fusiondirectory-plugins-1.3.1/
    - mv ./* ../fusiondirectory-plugins-1.3.1/
    - mv  ../fusiondirectory-plugins-1.3.1/ ./
    - tar -cvzf fusiondirectory-plugins-1.3.1.tar.gz *
  artifacts:
    paths:
      - fusiondirectory-plugins-1.3.1.tar.gz
    expire_in: 30d

build-release:
  stage: tarballs
  only:
    - tags
  script:
    - tar -cvzf fusiondirectory-plugins-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"').tar.gz *
  artifacts:
    paths:
      - fusiondirectory-plugins-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"').tar.gz

trigger-ci-debian-buster:
  stage: trigger
  only:
    - 1.3-fixes
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_DEBIAN_BUSTER: "$BRANCH_BUILD_DEBIAN_BUSTER"
  trigger:
    project: debian/buster-fusiondirectory-fixes
    branch: "$BRANCH_BUILD_DEBIAN_BUSTER"

trigger-ci-centos7:
  stage: trigger
  only:
    - 1.3-fixes
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_CENTOS_7: "$BRANCH_BUILD_CENTOS_7"
  trigger:
    project: centos/centos7-fusiondirectory-fixes
    branch: "$BRANCH_BUILD_CENTOS_7"
