stages:
  - lint
  - codestyle
  - manpages
  - transifex
  - tarballs
  - trigger

## Stage lint

# PHP lint
create_php_lint_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd/phpcodesniffer-cli:buster
  stage: lint
  only:
    - branches
  script:
    - find . -type f -name '*.php' -o -name '*.inc' -print0 | xargs -0 -n1 php -l

## Stage codestyle

# PHP codesniffer
create_php_code_sniffer_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd/phpcodesniffer-cli:buster
  stage: codestyle
  only:
    - branches
  script:
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - find . -type f -name '*.php' -o -name '*.inc' > ./filelist
    - /root/.composer/vendor/bin/phpcs --ignore=class_sieve.inc --standard=../dev-tools/php-codesniffer-rules/FDStandard/ruleset.xml --file-list=./filelist
    - /root/.composer/vendor/bin/phpcs --config-set installed_paths /PHPCompatibility,/PHPCSUtils
    - /root/.composer/vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion $PHP_COMPATIBILITY --file-list=./filelist

# phpstan
create_phpstan_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd/phpstan-cli:buster
  stage: codestyle
  only:
    - branches
  script:
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - test -d ../fusiondirectory/ && rm -Rf ../fusiondirectory/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/fd.git ../fusiondirectory
    - composer global require phpstan/phpstan=0.12.94
    - cp ../dev-tools/phpstan/fusiondirectory/1.4-dev/*.neon .
    - /root/.composer/vendor/bin/phpstan analyse -c phpstan-plugins.neon

# fusiondirectory-update-locale
fusiondirectory-update-locale:
  image: registry.fusiondirectory.org/fusiondirectory/fd/transifex-cli:buster
  stage: transifex
  only:
    - /^1.*$/
  script:
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - ../dev-tools/locale-scripts/fusiondirectory-update-locale-plugins

# Update transifex
update-transifex:
  image: registry.fusiondirectory.org/fusiondirectory/fd/transifex-cli:buster
  stage: transifex
  only:
    - /^1.*$/
  script:
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
    - tx pull -a
    - ../dev-tools/locale-scripts/fusiondirectory-update-locale-plugins
    - tx push -s -t --skip --no-interactive

build-tarballs:
  stage: tarballs
  only:
    variables:
    - $TARBALLS_TRIGGER_VERSION
  script:
    - mkdir ../fusiondirectory-plugins-$VERSION/
    - mv ./* ../fusiondirectory-plugins-$VERSION/
    - mv  ../fusiondirectory-plugins-$VERSION/ ./
    - tar -cvzf fusiondirectory-plugins-$VERSION.tar.gz *
  artifacts:
    paths:
      - fusiondirectory-plugins-$VERSION.tar.gz
    expire_in: 30d

trigger-ci-debian-buster:
  stage: trigger
  only:
    - $TARBALLS_TRIGGER_VERSION
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_DEBIAN_BUSTER: "$BRANCH_BUILD_DEBIAN_BUSTER"
  trigger:
    project: debian/buster-fusiondirectory-dev
    branch: "$BRANCH_BUILD_DEBIAN_BUSTER"

